version: '2'
services:
  mysql:
    user: mysql
    restart: always
    image: mysql:5.7.16
    container_name: mysql-server
#    network_mode: host
    networks:
      - rct_backend
    ports:
      - "3306:3306"
    volumes:
      - rct_mysql_data:/var/lib/mysql
      - rct_log:/var/log/mysql
#    ports:
#      - 33306:3306
#    networks:
#      - rct_backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
#    healthcheck:
#      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost",  "-u", "$$MYSQL_USER" , "--password=$$MYSQL_ROOT_PASSWORD"]
#      timeout: 20s
#      retries: 10

volumes:
  rct_mysql_data:
  rct_log:

networks:
  rct_backend:
    external: true
    driver: bridge
